import type {
  Circle,
  Conversation,
  FeedRecipe,
  Gathering,
  Message,
  Moment,
  Post,
  MiraUser,
  VaultItem,
} from "./mira";

const avatar = (seed: string) =>
  `https://api.dicebear.com/9.x/notionists/svg?seed=${encodeURIComponent(seed)}&backgroundColor=c8e6d8,d4e4f0,f0e6d8`;

const photo = (id: number, w = 800, h = 1000) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=${w}&h=${h}&q=80`;

export const MIRA_USERS: MiraUser[] = [
  {
    id: "u-you",
    handle: "du",
    name: "Du",
    bio: "Neugierig. Intentional. Hier, um zu verbinden – nicht zu scrollen.",
    avatar: avatar("mira-you"),
    cover: photo(1506905929186, 1600, 600),
    facets: ["personal", "craft", "public"],
    craft: "Gestaltung & Community",
    villageIds: ["u-lena", "u-jonas", "u-mira", "u-sam", "u-noah"],
    followerCount: 128,
    followingCount: 64,
    isYou: true,
  },
  {
    id: "u-lena",
    handle: "lena.wald",
    name: "Lena Wald",
    bio: "Fotografiert Morgenlicht. Baut kleine Rituale.",
    avatar: avatar("lena-wald"),
    cover: photo(1469474968028, 1600, 600),
    facets: ["personal", "craft"],
    craft: "Fotografie",
    villageIds: ["u-you", "u-jonas"],
    followerCount: 2400,
    followingCount: 190,
  },
  {
    id: "u-jonas",
    handle: "jonas.kite",
    name: "Jonas Kite",
    bio: "Product thinker. Liebt klare Systeme und laute Musik.",
    avatar: avatar("jonas-kite"),
    cover: photo(1519681393784, 1600, 600),
    facets: ["craft", "public"],
    craft: "Product Design",
    villageIds: ["u-you", "u-lena", "u-sam"],
    followerCount: 5100,
    followingCount: 320,
  },
  {
    id: "u-mira",
    handle: "mira.notes",
    name: "Mira Notes",
    bio: "Schreibt über Aufmerksamkeit und digitale Hygiene.",
    avatar: avatar("mira-notes"),
    cover: photo(1499750310169, 1600, 600),
    facets: ["public", "craft"],
    craft: "Essay & Research",
    villageIds: ["u-you"],
    followerCount: 8900,
    followingCount: 110,
  },
  {
    id: "u-sam",
    handle: "sam.orbit",
    name: "Sam Orbit",
    bio: "Community builder. Discord-native, IRL-first.",
    avatar: avatar("sam-orbit"),
    cover: photo(1529156069898, 1600, 600),
    facets: ["personal", "public"],
    craft: "Community",
    villageIds: ["u-you", "u-jonas", "u-noah"],
    followerCount: 3200,
    followingCount: 450,
  },
  {
    id: "u-noah",
    handle: "noah.reel",
    name: "Noah Reel",
    bio: "Kurze Filme. Lange Spaziergänge.",
    avatar: avatar("noah-reel"),
    cover: photo(1485846234645, 1600, 600),
    facets: ["craft", "personal"],
    craft: "Video",
    villageIds: ["u-you", "u-sam"],
    followerCount: 12000,
    followingCount: 88,
  },
  {
    id: "u-aya",
    handle: "aya.atelier",
    name: "Aya Atelier",
    bio: "Keramik, Tee, Stille.",
    avatar: avatar("aya-atelier"),
    cover: photo(1493106648143, 1600, 600),
    facets: ["craft"],
    craft: "Keramik",
    villageIds: [],
    followerCount: 6700,
    followingCount: 54,
  },
  {
    id: "u-elio",
    handle: "elio.code",
    name: "Elio Code",
    bio: "Open Source. Federated futures.",
    avatar: avatar("elio-code"),
    cover: photo(1517694712202, 1600, 600),
    facets: ["craft", "public"],
    craft: "Engineering",
    villageIds: [],
    followerCount: 15400,
    followingCount: 201,
  },
];

export const MIRA_CIRCLES: Circle[] = [
  {
    id: "c-atelier",
    name: "Atelier",
    slug: "atelier",
    description: "Für Maker:innen – Prozess zeigen, Feedback geben, gemeinsam wachsen.",
    cover: photo(1513364772260, 1200, 500),
    icon: "Palette",
    memberCount: 1842,
    joined: true,
    channels: [
      { id: "ch-1", name: "allgemein", kind: "chat" },
      { id: "ch-2", name: "prozesse", kind: "board" },
      { id: "ch-3", name: "critique", kind: "chat" },
      { id: "ch-4", name: "studio-call", kind: "voice" },
    ],
    tags: ["design", "craft", "kunst"],
  },
  {
    id: "c-signal",
    name: "Signal Lab",
    slug: "signal-lab",
    description: "Gedanken zu Medien, Aufmerksamkeit und digitalen Räumen.",
    cover: photo(1451187580459, 1200, 500),
    icon: "Radio",
    memberCount: 3201,
    joined: true,
    channels: [
      { id: "ch-5", name: "essays", kind: "board" },
      { id: "ch-6", name: "debatte", kind: "chat" },
      { id: "ch-7", name: "lesen", kind: "board" },
    ],
    tags: ["medien", "kultur", "tech"],
  },
  {
    id: "c-city",
    name: "Stadtspaziergang",
    slug: "stadtspaziergang",
    description: "Lokale Treffen, versteckte Orte, spontane Spaziergänge.",
    cover: photo(1449824913935, 1200, 500),
    icon: "MapPin",
    memberCount: 956,
    joined: false,
    channels: [
      { id: "ch-8", name: "termine", kind: "board" },
      { id: "ch-9", name: "tipps", kind: "chat" },
    ],
    tags: ["lokal", "treffen", "stadt"],
  },
  {
    id: "c-fokus",
    name: "Deep Work Club",
    slug: "deep-work",
    description: "Gemeinsam fokussieren. Kein Scroll, nur Flow.",
    cover: photo(1434030216411, 1200, 500),
    icon: "Focus",
    memberCount: 2104,
    joined: true,
    channels: [
      { id: "ch-10", name: "sessions", kind: "voice" },
      { id: "ch-11", name: "accountability", kind: "chat" },
    ],
    tags: ["produktivität", "fokus"],
  },
  {
    id: "c-taste",
    name: "Geschmack",
    slug: "geschmack",
    description: "Musik, Filme, Bücher – Empfehlungen ohne Algorithmus-Zwang.",
    cover: photo(1514525253161, 1200, 500),
    icon: "Headphones",
    memberCount: 5402,
    joined: false,
    channels: [
      { id: "ch-12", name: "musik", kind: "board" },
      { id: "ch-13", name: "film", kind: "board" },
      { id: "ch-14", name: "bücher", kind: "board" },
    ],
    tags: ["kultur", "empfehlungen"],
  },
];

export const MIRA_POSTS: Post[] = [
  {
    id: "p1",
    authorId: "u-lena",
    kind: "frame",
    facet: "personal",
    body: "Heute 6:12. Der Nebel hält die Stadt noch einen Moment länger fest.",
    mediaUrl: photo(1470071459604, 900, 1100),
    resonance: 128,
    replies: 14,
    echoes: 22,
    saved: false,
    resonated: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 42).toISOString(),
    tags: ["morgen", "licht", "stadt"],
  },
  {
    id: "p2",
    authorId: "u-jonas",
    kind: "signal",
    facet: "craft",
    body: "Feed-Rezepte > Feed-Algorithmen.\n\nWenn du die Absicht formulierst, bevor du öffnest, ändert sich alles. Weniger Dopamin, mehr Richtung.",
    resonance: 412,
    replies: 67,
    echoes: 89,
    saved: true,
    resonated: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 95).toISOString(),
    tags: ["design", "attention", "product"],
    circleId: "c-signal",
  },
  {
    id: "p3",
    authorId: "u-noah",
    kind: "pulse",
    facet: "craft",
    body: "30 Sekunden aus dem letzten Spaziergang – ohne Schnitt, ohne Musik.",
    mediaUrl: photo(1492691527719, 900, 1200),
    mediaPoster: photo(1492691527719, 900, 1200),
    resonance: 890,
    replies: 41,
    echoes: 120,
    saved: false,
    resonated: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
    tags: ["video", "drift", "alltag"],
  },
  {
    id: "p4",
    authorId: "u-mira",
    kind: "signal",
    facet: "public",
    body: "Die radikalste Social-Feature ist ein Ende.\n\nNähe-Modus: nur dein Dorf. Wenn alle gelesen haben, ist der Scroll zu Ende. Das ist kein Bug.",
    resonance: 1204,
    replies: 156,
    echoes: 310,
    saved: true,
    resonated: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
    tags: ["essay", "social", "dunbar"],
    circleId: "c-signal",
  },
  {
    id: "p5",
    authorId: "u-sam",
    kind: "truth",
    facet: "personal",
    body: "Truth-Fenster: Küche, ungewaschenes Geschirr, Playlist laut. Genau so.",
    mediaUrl: photo(1556911220, 800, 800),
    resonance: 56,
    replies: 8,
    echoes: 3,
    saved: false,
    resonated: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    tags: ["truth", "real"],
  },
  {
    id: "p6",
    authorId: "u-aya",
    kind: "frame",
    facet: "craft",
    body: "Glasur-Versuch #7. Zu viel Kupfer – aber die Kante mag ich.",
    mediaUrl: photo(1565193569085, 900, 1100),
    resonance: 334,
    replies: 29,
    echoes: 45,
    saved: false,
    resonated: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 400).toISOString(),
    tags: ["keramik", "prozess", "atelier"],
    circleId: "c-atelier",
  },
  {
    id: "p7",
    authorId: "u-elio",
    kind: "signal",
    facet: "craft",
    body: "Federated identity + intentional feeds = das fehlende Stück zwischen Bluesky und Discord.\n\nWer baut mit?",
    resonance: 678,
    replies: 92,
    echoes: 140,
    saved: false,
    resonated: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 520).toISOString(),
    tags: ["opensource", "federation", "build"],
    circleId: "c-signal",
  },
  {
    id: "p8",
    authorId: "u-jonas",
    kind: "frame",
    facet: "personal",
    body: "Whiteboard nach dem Deep-Work-Block. Drei Entscheidungen, null Meetings.",
    mediaUrl: photo(1531403009284, 900, 700),
    resonance: 201,
    replies: 18,
    echoes: 27,
    saved: true,
    resonated: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    tags: ["fokus", "arbeit"],
    circleId: "c-fokus",
  },
  {
    id: "p9",
    authorId: "u-lena",
    kind: "signal",
    facet: "personal",
    body: "Wer hat Lust auf einen stillen Spaziergang Sonntag 10 Uhr? Keine Agenda.",
    resonance: 44,
    replies: 12,
    echoes: 5,
    saved: false,
    resonated: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    tags: ["treffen", "stadt"],
    circleId: "c-city",
  },
  {
    id: "p10",
    authorId: "u-noah",
    kind: "pulse",
    facet: "public",
    body: "Wie man einen Schnitt spürt, bevor man ihn sieht.",
    mediaUrl: photo(1478720568477, 900, 1200),
    resonance: 2100,
    replies: 88,
    echoes: 400,
    saved: false,
    resonated: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 800).toISOString(),
    tags: ["film", "craft", "drift"],
  },
];

export const MIRA_MOMENTS: Moment[] = [
  {
    id: "m1",
    authorId: "u-lena",
    mediaUrl: photo(1469474968028, 600, 900),
    caption: "Nebel",
    createdAt: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 20).toISOString(),
    viewed: false,
  },
  {
    id: "m2",
    authorId: "u-jonas",
    mediaUrl: photo(1519681393784, 600, 900),
    caption: "Skyline",
    createdAt: new Date(Date.now() - 1000 * 60 * 55).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 18).toISOString(),
    viewed: false,
  },
  {
    id: "m3",
    authorId: "u-sam",
    mediaUrl: photo(1529156069898, 600, 900),
    caption: "Meetup",
    createdAt: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 12).toISOString(),
    viewed: true,
  },
  {
    id: "m4",
    authorId: "u-noah",
    mediaUrl: photo(1485846234645, 600, 900),
    caption: "Set",
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 8).toISOString(),
    viewed: true,
  },
  {
    id: "m5",
    authorId: "u-aya",
    mediaUrl: photo(1493106648143, 600, 900),
    caption: "Ofen",
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 22).toISOString(),
    viewed: false,
  },
];

export const MIRA_RECIPES: FeedRecipe[] = [
  {
    id: "r1",
    name: "Ruhiger Morgen",
    description: "Nur Frames & Signals aus Nähe und Craft – keine Drift-Hits.",
    intent: "Ich will sanft starten und inspiriert werden, ohne Reizüberflutung.",
    sources: ["village", "circles"],
    includeTags: ["morgen", "licht", "prozess", "craft"],
    excludeTags: ["viral", "drama"],
    preferKinds: ["frame", "signal"],
    active: true,
  },
  {
    id: "r2",
    name: "Craft Deep Dive",
    description: "Atelier + Fokus: Prozesse, Kritik, Deep Work.",
    intent: "Ich will an meinem Handwerk wachsen.",
    sources: ["circles", "following"],
    includeTags: ["prozess", "design", "fokus", "keramik", "film"],
    excludeTags: [],
    preferKinds: ["frame", "signal", "pulse"],
    active: false,
  },
  {
    id: "r3",
    name: "Neugier Drift",
    description: "Entdeckung mit Absicht – Pulse & öffentliche Signals.",
    intent: "Zeig mir Neues, das zu meinen Interessen passt – nicht was alle anschreien.",
    sources: ["discovery", "circles"],
    includeTags: ["drift", "kultur", "opensource", "essay"],
    excludeTags: ["ragebait"],
    preferKinds: ["pulse", "signal"],
    active: false,
  },
];

export const MIRA_CONVERSATIONS: Conversation[] = [
  {
    id: "cv1",
    participantIds: ["u-you", "u-lena"],
    lastMessage: "Sonntag Spaziergang – bist du dabei?",
    updatedAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
    unread: 2,
  },
  {
    id: "cv2",
    participantIds: ["u-you", "u-jonas"],
    lastMessage: "Hab das Feed-Rezept geteilt – schau mal r2.",
    updatedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    unread: 0,
  },
  {
    id: "cv3",
    participantIds: ["u-you", "u-sam"],
    lastMessage: "Deep Work Session um 15 Uhr im Circle.",
    updatedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    unread: 1,
  },
];

export const MIRA_MESSAGES: Message[] = [
  {
    id: "msg1",
    conversationId: "cv1",
    senderId: "u-lena",
    body: "Hey! Der Nebel heute morgen war wahnsinnig.",
    createdAt: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
  },
  {
    id: "msg2",
    conversationId: "cv1",
    senderId: "u-lena",
    body: "Sonntag Spaziergang – bist du dabei?",
    createdAt: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
  },
  {
    id: "msg3",
    conversationId: "cv2",
    senderId: "u-jonas",
    body: "Hab das Feed-Rezept geteilt – schau mal r2.",
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: "msg4",
    conversationId: "cv3",
    senderId: "u-sam",
    body: "Deep Work Session um 15 Uhr im Circle.",
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },
];

export const MIRA_GATHERINGS: Gathering[] = [
  {
    id: "g1",
    title: "Stiller Sonntagsspaziergang",
    description: "Keine Agenda. Einfach gehen und schauen.",
    when: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    where: "Stadtpark, Nordtor",
    circleId: "c-city",
    hostId: "u-lena",
    attendeeCount: 7,
    going: false,
  },
  {
    id: "g2",
    title: "Critique Night – Atelier",
    description: "Bring ein Work-in-Progress. Feedback nach Chatham House.",
    when: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    where: "Online · Voice Channel",
    circleId: "c-atelier",
    hostId: "u-aya",
    attendeeCount: 18,
    going: true,
  },
  {
    id: "g3",
    title: "Deep Work Block · 90 Min",
    description: "Kameras optional. Timer. Stille.",
    when: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
    where: "Deep Work Club · sessions",
    circleId: "c-fokus",
    hostId: "u-sam",
    attendeeCount: 24,
    going: false,
  },
];

export const MIRA_VAULT: VaultItem[] = [
  {
    id: "v1",
    postId: "p2",
    collection: "Ideen",
    savedAt: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: "v2",
    postId: "p4",
    collection: "Essays",
    savedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
  },
  {
    id: "v3",
    postId: "p8",
    collection: "Fokus",
    savedAt: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
  },
];
