export const SITE = {
  name: "NachtBlau Crew",
  shortName: "NachtBlau",
  tagline: "Deine Gaming Community für PC, Konsolen, Steam und mehr.",
  description:
    "NachtBlau Crew – Deine Gaming Community für PC, Konsolen, Steam und mehr. Aktuelle News, kostenlose Spiele und ein aktives Forum.",
  logoUrl:
    "https://d2xsxph8kpxj0f.cloudfront.net/310519663739653758/PbtcqHtcftAKnwDnhmoduf/nachtblau-logo-Li7umgFb8XhrYaRtYVFm4Z.webp",
  heroBgUrl:
    "https://d2xsxph8kpxj0f.cloudfront.net/310519663739653758/PbtcqHtcftAKnwDnhmoduf/nachtblau-hero-bg-HgRTyjrF5BBTepdctiJ8Mj.webp",
  webspaceUrl: "https://nacht-blau.de",
  webspaceLabel: "NachtBlau Webspace",
  hybrixonUrl: "https://hybrixon.com",
  hybrixonLabel: "Hybrixon",
  hybrixonAppUrl: "https://hybrixon.com/app.php",
  githubUrl: "https://github.com/Wuza0295/nachtblau-crew",
  githubOrgUrl: "https://github.com/Wuza0295",
  githubLabel: "GitHub Repository",
  contactEmail: "info@nacht-blau.de",
  gamerPowerUrl: "https://www.gamerpower.com",
} as const;

/** Live-Projekte auf dem ALL-INKL-Webspace (w02176b7.kasserver.com). */
export const WEBSPACE_PROJECTS = [
  {
    id: "hybrixon",
    title: "Hybrixon",
    subtitle: "Social Network · Closer. Freer.",
    url: SITE.hybrixonUrl,
    host: "hybrixon.com",
    note: "PHP-Social mit Feed, Shorts, Stories, Gruppen, Suche, PWA und Android-APK 1.0.4.",
    live: true,
  },
  {
    id: "nachtblau-gbr",
    title: "NachtBlau GbR",
    subtitle: "Gesellschaftsseite",
    url: SITE.webspaceUrl,
    host: "nacht-blau.de",
    note: "GbR-Profil, Impressum, Datenschutz und Allxion unter /allxion/.",
    live: true,
  },
  {
    id: "allxion",
    title: "Allxion",
    subtitle: "Hybrid-Social-Hub · NachtBlau Crew",
    url: `${SITE.webspaceUrl}/allxion/`,
    host: "nacht-blau.de",
    note: "React-App auf dem GbR-Webspace.",
    live: true,
  },
  {
    id: "nachtblau-crew",
    title: "NachtBlau Crew",
    subtitle: "Gaming-Gilde",
    url: "https://nachtblau-crew.de",
    host: "nachtblau-crew.de",
    note: "Öffentliche Gilden-Seite.",
    live: true,
  },
  {
    id: "nachtblau-interactive",
    title: "NachtBlau Interactive",
    subtitle: "Game Studio & Publisher",
    url: "https://nachtblau-interactive.com",
    host: "nachtblau-interactive.com",
    note: "Studio-Seite; Hub unter launcher.nachtblau-interactive.com.",
    live: true,
  },
  {
    id: "nachtblau-hub",
    title: "NachtBlau Hub",
    subtitle: "Launcher v26 · Web, Linux, Android",
    url: "https://launcher.nachtblau-interactive.com",
    host: "launcher.nachtblau-interactive.com",
    note: "linux.html und android.html laden live vom Webspace.",
    live: true,
  },
  {
    id: "autic-treasures",
    title: "Autic Treasures",
    subtitle: "Trading-Card-Community",
    url: "https://autic-treasures.com",
    host: "autic-treasures.com",
    note: "Spiegel: autictreasures.nacht-blau.de.",
    live: true,
  },
  {
    id: "black-horizon",
    title: "Black Horizon",
    subtitle: "PROJECT: BLACK HORIZON",
    url: "https://blackhorizon.info",
    host: "blackhorizon.info",
    note: "Projektseite auf demselben ALL-INKL-Account.",
    live: true,
  },
  {
    id: "noxcast",
    title: "NoxCast",
    subtitle: "Startseite",
    url: "https://noxcast.com",
    host: "noxcast.com",
    note: "Webspace-Domain.",
    live: true,
  },
  {
    id: "ram-imbiss",
    title: "RAM-Imbiss",
    subtitle: "Imbisswagen",
    url: "https://ram-imbiss.at",
    host: "ram-imbiss.at",
    note: "Webspace-Domain.",
    live: true,
  },
  {
    id: "iron-front",
    title: "Iron Front",
    subtitle: "Panzer-Schlacht",
    url: "http://iron-front.nachtblau-interactive.com",
    host: "iron-front.nachtblau-interactive.com",
    note: "Live per HTTP; HTTPS-Zertifikat passt nicht zur Subdomain.",
    live: true,
  },
] as const;

export const EXTERNAL_LINKS = [
  {
    href: SITE.webspaceUrl,
    label: SITE.webspaceLabel,
    description: "Offizielle Website der NachtBlau GbR mit Infos zum Projekt und Team.",
    external: true,
  },
  {
    href: SITE.hybrixonUrl,
    label: SITE.hybrixonLabel,
    description:
      "Hybrixon auf dem ALL-INKL-Webspace: Social Feed, App-Download, Shorts, Stories und Gruppen.",
    external: true,
  },
  {
    href: SITE.githubUrl,
    label: SITE.githubLabel,
    description: "Quellcode, Issues und Beiträge zur NachtBlau Crew App auf GitHub.",
    external: true,
  },
  {
    href: `mailto:${SITE.contactEmail}`,
    label: "Kontakt",
    description: "Schreib uns eine E-Mail an info@nacht-blau.de.",
    external: true,
  },
] as const;
